name: Quality Gates

on:
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        
    - name: Check test coverage threshold
      run: |
        pytest tests/ --cov=src --cov-fail-under=85
        
    - name: Check code complexity
      run: |
        radon cc src --min B  # Complexity threshold
        
    - name: Check documentation coverage
      run: |
        interrogate src --ignore-init-method --ignore-module --fail-under=80
        
    - name: Performance regression test
      run: |
        pytest tests/performance/ --benchmark-only
        
    - name: Security vulnerability scan
      run: |
        safety check
        bandit -r src -f json -o bandit-report.json
        
    - name: Generate quality report
      run: |
        python scripts/generate_quality_report.py
        
    - name: Comment PR with results
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('quality-report.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: report
          });
